apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SEMAPHORE_DB_USER: {{ .Values.secret.SEMAPHORE_DB_USER }}
  SEMAPHORE_DB_PASS: {{ .Values.secret.SEMAPHORE_DB_PASS }}
  SEMAPHORE_ADMIN_PASSWORD: {{ .Values.secret.SEMAPHORE_ADMIN_PASSWORD }}
  SEMAPHORE_ADMIN_NAME: {{ .Values.secret.SEMAPHORE_ADMIN_NAME }}
  SEMAPHORE_LDAP_PASSWORD: {{ .Values.secret.SEMAPHORE_LDAP_PASSWORD }}
